name: WolfyMachines
author: JasperChaseTOQ
description: A dev slimefun addon
main: me.jasperchasetoq.wolfymachines.WolfyMachines
website: https://github.com/JasperChaseTOQ/WolfyMachines
version: ${project.version}
api-version: 1.17
depend: [Slimefun]